name: Pages

on:
  push:
    branches:
      - master

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: prepare
        run: |
          git config --global user.name "Sergio Carracedo"
          git config --global user.email "hi@sergiocarracedo.es"
          sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml
          sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
          git submodule update --init --recursive
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: yarn install && yarn --cwd "themes/phpvigo"
      - name: Get events
        run: yarn prepare-json
        env:
          MEMBER: phpvigo
          GENERATED_JSON_PATH: source/phpvigo.json
          MEETUP_API_BASE: http://api.meetup.com
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          EVENTBRITE_OAUTH_TOKEN: ${{ secrets.EVENTBRITE_OAUTH_TOKEN }}
      - name: Build
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
